# Shared AWS provider configuration for live descendant stacks.
#
# Include from a stack with:
#   include "provider" {
#     path   = find_in_parent_folders("_envcommon/provider.hcl")
#     expose = true
#   }
#
# Account and region targeting remains a property of the consuming hierarchy.
# This layer must not assume credentials, account IDs, or regions that are not
# present in the catalogs or the stack's account/region metadata.

locals {
  repository_root = get_repo_root()
  live_root       = "${local.repository_root}/live"

  common = try(
    read_terragrunt_config("${local.live_root}/common.hcl"),
    {}
  )
  common_locals = try(local.common.locals, {})

  # These files are optional until the corresponding account/region hierarchy
  # is created. A missing value is retained as null for consumers, while the
  # generated provider receives an invalid sentinel so AWS_REGION cannot
  # silently redirect an unresolved stack.
  region_config = try(
    read_terragrunt_config(find_in_parent_folders("region.hcl")),
    {}
  )
  account_config = try(
    read_terragrunt_config(find_in_parent_folders("account.hcl")),
    {}
  )

  region_locals  = try(local.region_config.locals, {})
  account_locals = try(local.account_config.locals, {})

  aws_region = try(
    local.region_locals.aws_region,
    local.region_locals.region,
    local.region_locals.name,
    null
  )
  provider_region = (
    try(trimspace(tostring(local.aws_region)), "") != ""
    ? local.aws_region
    : "__unresolved_region__"
  )

  account_key = try(
    local.account_locals.account_key,
    local.account_locals.account_name,
    local.account_locals.name,
    null
  )
  account_id = try(
    local.account_locals.account_id,
    try(local.common_locals.account_ids[local.account_key], null),
    null
  )

  # Provider default tags intentionally use only the shared catalog tags.
  # Environment/account/component tags remain stack inputs so this layer does
  # not duplicate or override a future tagging.hcl implementation.
  default_tags = try(local.common_locals.common_tags, {})

  provider_context = {
    account_key = local.account_key
    account_id  = local.account_id
    region      = local.aws_region
  }
}

generate "aws_provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<-EOF
    # Generated by Terragrunt from live/_envcommon/provider.hcl.
    # Do not edit this file directly.
    provider "aws" {
      region = ${jsonencode(local.provider_region)}

      default_tags {
        tags = ${jsonencode(local.default_tags)}
      }
    }
  EOF
}
