# Bootstrap-only stack for the Terraform remote-state infrastructure.
#
# This stack intentionally does not include _envcommon/remote-state.hcl. The
# backend it creates does not exist during the first apply, so Terraform uses
# local state until an explicit, reviewed migration is performed.

include "root" {
  path   = find_in_parent_folders("terragrunt.hcl")
  expose = true
}

include "tagging" {
  path           = find_in_parent_folders("_envcommon/tagging.hcl")
  expose         = true
  merge_strategy = "deep"
}

locals {
  common = try(include.root.locals.common_locals, {})

  module_name   = "backend-bootstrap"
  module_source = try(include.root.locals.module_sources[local.module_name], null)

  # Backend ownership and encryption metadata must be populated from an
  # approved catalog projection before deployment. No caller identity,
  # environment variable, or guessed identifier is used as a fallback.
  bootstrap_config = try(
    local.common.bootstrap.backend,
    local.common.backend.bootstrap,
    local.common.backend,
    {}
  )

  account_key = try(local.bootstrap_config.account_key, null)
  account_id = try(
    include.root.locals.active_accounts[local.account_key],
    null
  )
  aws_region = try(
    local.bootstrap_config.region,
    local.bootstrap_config.aws_region,
    null
  )
  name_prefix = try(local.bootstrap_config.name_prefix, null)
  kms_key_arn = try(
    local.bootstrap_config.kms_key_arn,
    local.bootstrap_config.kms_key_id,
    null
  )

  # Invalid sentinels prevent the AWS provider from silently accepting ambient
  # account or Region context while the catalog metadata is unresolved.
  provider_region = (
    try(trimspace(tostring(local.aws_region)), "") != ""
    ? local.aws_region
    : "__unresolved_region__"
  )
  allowed_account_ids = (
    local.account_id != null
    && can(regex("^[0-9]{12}$", tostring(local.account_id)))
    ? [tostring(local.account_id)]
    : ["__unresolved_account__"]
  )

  tags                  = try(include.tagging.locals.tags, {})
  provider_default_tags = try(include.root.locals.common_tags, {})

  _regions_config        = read_terragrunt_config(find_in_parent_folders("catalogs/regions.hcl"))
  _primary_region        = [for k, v in local._regions_config.locals.regions : k if v.primary == true][0]
  _gen_region_json       = jsonencode(local._primary_region)
  _account_id            = try(get_aws_account_id(), "000000000000")
  _gen_account_ids_json  = jsonencode([local._account_id])
  _gen_default_tags_json = jsonencode(local.provider_default_tags)
}

terraform {
  source = local.module_source
}

# The normal provider layer expects account.hcl and region.hcl in a descendant
# hierarchy. Bootstrap is intentionally outside that hierarchy, so it owns one
# isolated provider file with the same credential-chain and default-tag model.
generate "bootstrap_aws_provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<-EOF
    # Generated by Terragrunt for the backend bootstrap stack.
    # Do not edit this file directly.
    provider "aws" {
      region              = ${local._gen_region_json}
      allowed_account_ids = ${local._gen_account_ids_json}

      default_tags {
        tags = ${local._gen_default_tags_json}
      }
    }
  EOF
}

inputs = {
  name_prefix = local.name_prefix
  environment = "shared"
  kms_key_arn = local.kms_key_arn
  tags        = local.tags

  enable_access_logging              = true
  access_logs_retention_days         = 365
  noncurrent_version_expiration_days = 90
  noncurrent_versions_to_retain      = 10
  enable_deletion_protection         = true
  force_destroy                      = false
}
