# Sandbox IAM validation identity for repository-controlled smoke tests.
#
# The reusable identity module supports GitHub Actions OIDC roles only. This
# stack therefore owns the sandbox account's GitHub OIDC provider and one
# repository-scoped, read-only role for validating IAM configuration.

include "region" {
  path   = find_in_parent_folders("region.hcl")
  expose = true
}

include "remote_state" {
  path = find_in_parent_folders("_envcommon/remote-state.hcl")
}

include "tagging" {
  path           = find_in_parent_folders("_envcommon/tagging.hcl")
  expose         = true
  merge_strategy = "deep"
}

locals {
  common = read_terragrunt_config(
    "${get_repo_root()}/live/common.hcl"
  )
  common_locals = try(local.common.locals, {})

  module_name = "github-oidc"
  module_source = try(
    local.common_locals.module_sources[local.module_name],
    null
  )

  account_id = try(include.region.locals.account_id, null)
  allowed_sandbox_account_ids = (
    local.account_id != null
    && can(regex("^[0-9]{12}$", tostring(local.account_id)))
    ? [tostring(local.account_id)]
    : ["__unresolved_sandbox_account__"]
  )

  provider_region = try(
    include.region.locals.aws_region,
    include.region.locals.region,
    include.region.locals.name,
    "__unresolved_region__"
  )

  # Derive the GitHub owner/repository from the shared repository catalog
  # value instead of duplicating it in the trust policy.
  repository_url = try(
    local.common_locals.organization.repository,
    null
  )
  github_repository = (
    local.repository_url != null
    && startswith(local.repository_url, "github.com/")
    ? trimprefix(local.repository_url, "github.com/")
    : "__unresolved_repository__"
  )
  validation_subject = "repo:${local.github_repository}:ref:refs/heads/main"

  iam_validation_policy = jsonencode({
    Version = "2012-10-17"

    Statement = [
      {
        Sid    = "InspectIAMConfiguration"
        Effect = "Allow"
        Action = [
          "iam:GetAccountAuthorizationDetails",
          "iam:GetAccountPasswordPolicy",
          "iam:GetAccountSummary",
          "iam:GetOpenIDConnectProvider",
          "iam:GetPolicy",
          "iam:GetPolicyVersion",
          "iam:GetRole",
          "iam:GetRolePolicy",
          "iam:ListAttachedRolePolicies",
          "iam:ListOpenIDConnectProviders",
          "iam:ListPolicies",
          "iam:ListPolicyVersions",
          "iam:ListRolePolicies",
          "iam:ListRoles",
          "iam:ListUsers",
        ]
        Resource = "*"
      },
      {
        Sid      = "VerifyCallerIdentity"
        Effect   = "Allow"
        Action   = ["sts:GetCallerIdentity"]
        Resource = "*"
      },
    ]
  })
}

terraform {
  source = local.module_source
}

# IAM resources are account-global, but the AWS provider still requires a
# Region. The account allow-list prevents this identity stack from creating
# roles in management, security, log-archive, or another workload account.
# Until the sandbox catalog contains a real account ID, AWS operations fail
# closed against the deliberately invalid allow-list value.
generate "sandbox_aws_provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<-EOF
    # Generated by Terragrunt for the sandbox test IAM role stack.
    provider "aws" {
      region              = ${jsonencode(local.provider_region)}
      allowed_account_ids = ${jsonencode(local.allowed_sandbox_account_ids)}

      default_tags {
        tags = ${jsonencode(try(include.tagging.locals.tags, {}))}
      }
    }
  EOF
}

inputs = {
  # Each AWS account requires its own IAM OIDC provider. The management
  # account's provider cannot be referenced by a sandbox-account role.
  create_oidc_provider = true
  audiences            = ["sts.amazonaws.com"]
  role_path            = "/github-actions/test/"

  roles = {
    iam_validation = {
      name        = "sandbox-iam-validation"
      description = "Read-only IAM configuration validation from the platform-live-infra main branch."

      # Exact subject matching avoids repository, branch, tag, or pull-request
      # wildcards. GitHub's audience is restricted by the module input above.
      subjects         = [local.validation_subject]
      subject_patterns = []

      max_session_duration = 3600
      managed_policy_arns  = []
      inline_policies = {
        IAMConfigurationReadOnly = local.iam_validation_policy
      }

      tags = {
        Component = "test-iam-roles"
        Purpose   = "iam-validation"
      }
    }
  }

  tags = merge(
    {
      Component = "test-iam-roles"
    },
    try(include.tagging.locals.tags, {})
  )
}
