# Sandbox workload-account regional guardrail.
#
# The SCP module owns one policy document per state. This stack creates the
# sandbox region-restriction policy and attaches it to the sandbox account once
# the account catalog contains its real AWS account ID.

include "region" {
  path   = find_in_parent_folders("region.hcl")
  expose = true
}

include "remote_state" {
  path = find_in_parent_folders("_envcommon/remote-state.hcl")
}

include "tagging" {
  path           = find_in_parent_folders("_envcommon/tagging.hcl")
  expose         = true
  merge_strategy = "deep"
}

locals {
  common = read_terragrunt_config(
    "${get_repo_root()}/live/common.hcl"
  )
  common_locals = try(local.common.locals, {})

  module_name = "scp"
  module_source = try(
    local.common_locals.module_sources[local.module_name],
    null
  )

  policy_name = "sandbox-restrict-regions"
  policy_path = "${get_repo_root()}/policies/scp/restrict-regions.json"

  # Account metadata is inherited from the sandbox account/region hierarchy.
  # Until the catalog's TBD value is replaced with a real account ID, create
  # the policy without attachments rather than passing an invalid target ID.
  account_id = try(include.region.locals.account_id, null)
  target_ids = (
    local.account_id != null
    && can(regex("^[0-9]{12}$", tostring(local.account_id)))
    ? [tostring(local.account_id)]
    : []
  )

  # AWS Organizations SCP APIs must be called from the management account.
  # The catalog currently contains a TBD management ID, so use a deliberately
  # invalid provider allow-list sentinel until that value is populated.
  management_account_id = try(
    local.common_locals.account_ids.management,
    null
  )
  allowed_management_account_ids = (
    local.management_account_id != null
    && can(regex("^[0-9]{12}$", tostring(local.management_account_id)))
    ? [tostring(local.management_account_id)]
    : ["__unresolved_management_account__"]
  )

  provider_region = try(
    include.region.locals.aws_region,
    include.region.locals.region,
    include.region.locals.name,
    "__unresolved_region__"
  )
}

terraform {
  source = local.module_source
}

# SCP creation and attachment are organization-level operations and therefore
# require credentials for the AWS Organizations management account. The
# allow-list prevents accidental execution against the sandbox account or any
# other account when the management ID is unresolved.
generate "management_aws_provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"

  contents = <<-EOF
    # Generated by Terragrunt for the sandbox SCP attachment stack.
    # Credentials must resolve to the Organizations management account.
    provider "aws" {
      region              = ${jsonencode(local.provider_region)}
      allowed_account_ids = ${jsonencode(local.allowed_management_account_ids)}

      default_tags {
        tags = ${jsonencode(try(include.tagging.locals.tags, {}))}
      }
    }
  EOF
}

inputs = {
  name           = local.policy_name
  description    = "Restrict sandbox-account workloads to approved AWS Regions."
  policy_content = file(local.policy_path)

  # Attachments remain empty while sandbox.account_id is TBD. Once replaced,
  # the same state deterministically attaches this SCP to that account only.
  target_ids = local.target_ids

  # Keep the policy under Terraform ownership so policy changes are reviewed,
  # planned, and applied through this stack.
  skip_destroy = false

  tags = try(include.tagging.locals.tags, {})
}
